[workspace]
members = [
    "debug-listener",
    "exponential_distribution",
    "fan-controller",
    "home_assistant_discovery",
    "mqtt",
    "topic",
]
resolver = "3"

[workspace.dependencies]
defmt = { version = "1.0.1" }
